[www]
; Usuario y grupo de Linux que ejecutará los procesos de PHP
; suele ser www-data para servicios web. No queremos que se ejecute como root por que si hackean la web tendrian 
; ...control total sobre el contenedor. Al usar www-data solo pueden romper dentro de la web.
user = www-data
group = www-data

; Puerto donde PHP escuchará las peticiones que le envíe Nginx
listen = 9000
listen.owner = www-data
listen.group = www-data

; Gestión de procesos (cuántos "PHPs" hay encendidos a la vez)
pm = dynamic

; Máximo número de procesos hijos (para no agotar la RAM)
pm.max_children = 5

; Procesos que se lanzan nada más arrancar
pm.start_servers = 2

; Mínimo y máximo de procesos en espera
pm.min_spare_servers = 1
pm.max_spare_servers = 3
