server {
    # Escuchamos solo en el puerto 443 (SSL)
    listen 443 ssl;
    listen [::]:443 ssl;

    # Dominio
	server_name jrollon-.42.fr;

    # Rutas de los certificados que creamos en el Dockerfile
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocolos de seguridad (TLS v1.2 o v1.3 son obligatorios)
    ssl_protocols TLSv1.2 TLSv1.3;

    # Directorio raíz y archivos de índice
    root /var/www/wordpress;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    # Configuración para que Nginx pase el PHP a WordPress
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}
