server {
    # Escuchamos solo en el puerto 443 (SSL). el primero es ipv4 el segundo ipv6
    listen 443 ssl;
    listen [::]:443 ssl;

    # Dominio. que debe coincidir con el CN de openssl en el dockerfile.
	server_name jrollon-.42.fr;

    # Rutas de los certificados que creamos en el Dockerfile
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocolos de seguridad (TLS v1.2 o v1.3 son obligatorios)
    ssl_protocols TLSv1.2 TLSv1.3;

    # Directorio raíz y archivos de índice. root debe coincidir con el WORKDIR del dockerfile de wordpress
    root /var/www/wordpress;
    index index.php index.html index.htm;

    # config de Nginx para qué hacer cuando alguien pide archivo (index.html) o imagen. se lee de izda a dcha.
    # $uri busca el archivo exacto con el nombre pedido
    # $uri/ busca una carpeta con dicho nombre
    # si no lo encuentra dará error not found 404.
    location / {
        try_files $uri $uri/ =404;
    }

    # Configuración para que Nginx pase el PHP a WordPress
    # Nginx no sabe leer .php (solo entiende HTML). Se necesita el traductor
    # location ~ \.php$ = si alguien pide un archivo PHP ejecuta lo siguiente (entre llaves)
    # include snippets/fastcgi-php.conf; - importa un archivo de nginx para que el PHP funcione correctamente
    # fastcgi_pass wordpress:9000; - no se leer el archivo asi que pasalo a un contenedor llamado wordpress por el puerto 9000 que
    # ...fue puesto en el www.conf de wordpress.
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}
