// Normalized coordinates (0-1 range) - canvas-size agnostic
const TERRITORIES_NORMALIZED = {
  // --- NORTH (Top) ---
  scotland: {
    name: 'Scotland',
    capital: 'Glasgow',
    isRegCapital: false,
    impassable: false,
    colorKey: '#cccc33',
    nx: 0.2875,
    ny: 0.09375,
    neighbors: ['england', 'norway', 'ireland'],
  },
  ireland: {
    name: 'Ireland',
    capital: 'Dublin',
    isRegCapital: false,
    impassable: false,
    colorKey: '#05ff23',
    nx: 0.2,
    ny: 0.1775,
    neighbors: ['england', 'scotland'],
  },
  england: {
    name: 'England',
    capital: 'London',
    isRegCapital: true,
    impassable: false,
    colorKey: '#ff4005',
    nx: 0.29333,
    ny: 0.25,
    neighbors: ['scotland', 'ireland', 'batavia', 'portugal'],
  },
  norway: {
    name: 'Norway',
    capital: 'Oslo',
    isRegCapital: false,
    impassable: false,
    colorKey: '#ff9905',
    nx: 0.475,
    ny: 0.04125,
    neighbors: ['sweden', 'denmark', 'scotland'],
  },
  sweden: {
    name: 'Sweden',
    capital: 'Stockholm',
    isRegCapital: true,
    impassable: false,
    colorKey: '#4a66f7',
    nx: 0.5875,
    ny: 0.0525,
    neighbors: ['norway', 'denmark', 'baltic_states'],
  },
  denmark: {
    name: 'Denmark',
    capital: 'Copenhagen',
    isRegCapital: false,
    impassable: false,
    colorKey: '#ff5d05',
    nx: 0.4875,
    ny: 0.1875,
    neighbors: ['sweden', 'norway', 'hanover'],
  },

  // --- WEST (France and Iberia) ---
  france: {
    name: 'France',
    capital: 'Paris',
    isRegCapital: true,
    impassable: false,
    colorKey: '#010ce1',
    nx: 0.3125,
    ny: 0.375,
    neighbors: ['belgium', 'helvetia', 'piemonte', 'catalonia'],
  },
  catalonia: {
    name: 'Catalonia',
    capital: 'Barcelona',
    isRegCapital: false,
    impassable: false,
    colorKey: '#f4a398',
    nx: 0.28167,
    ny: 0.59375,
    neighbors: ['france', 'spain'],
  },
  spain: {
    name: 'Spain',
    capital: 'Madrid',
    isRegCapital: true,
    impassable: false,
    colorKey: '#2841fe',
    nx: 0.1625,
    ny: 0.615,
    neighbors: ['catalonia', 'portugal', 'barbary'],
  },
  portugal: {
    name: 'Portugal',
    capital: 'Lisbon',
    isRegCapital: false,
    impassable: false,
    colorKey: '#64fa00',
    nx: 0.05,
    ny: 0.625,
    neighbors: ['spain', 'england'],
  },

  // --- CENTER (Germany and Benelux) ---
  batavia: {
    name: 'Batavia',
    capital: 'Amsterdam',
    isRegCapital: true,
    impassable: false,
    colorKey: '#5bf9a5',
    nx: 0.3875,
    ny: 0.25,
    neighbors: ['belgium', 'hanover', 'rhine_west', 'england'],
  },
  belgium: {
    name: 'Belgium',
    capital: 'Waterloo',
    isRegCapital: false,
    impassable: false,
    colorKey: '#ef6394',
    nx: 0.38167,
    ny: 0.3125,
    neighbors: ['france', 'batavia', 'rhine_west'],
  },
  hanover: {
    name: 'Hanover',
    capital: 'Hanover',
    isRegCapital: false,
    impassable: false,
    colorKey: '#eec400',
    nx: 0.45,
    ny: 0.25,
    neighbors: ['batavia', 'denmark', 'brandenburg', 'saxony', 'rhine_west'],
  },
  rhine_west: {
    name: 'Rhineland',
    capital: 'Cologne',
    isRegCapital: false,
    impassable: false,
    colorKey: '#9f4dfb',
    nx: 0.43167,
    ny: 0.3125,
    neighbors: ['belgium', 'hanover', 'batavia', 'saxony', 'bavaria'],
  },
  saxony: {
    name: 'Saxony',
    capital: 'Dresden',
    isRegCapital: false,
    impassable: false,
    colorKey: '#f5e2d1',
    nx: 0.5,
    ny: 0.29125,
    neighbors: ['rhine_west', 'hanover', 'brandenburg', 'bohemia', 'bavaria'],
  },
  bavaria: {
    name: 'Bavaria',
    capital: 'Munich',
    isRegCapital: false,
    impassable: false,
    colorKey: '#98e8f4',
    nx: 0.475,
    ny: 0.41625,
    neighbors: ['rhine_west', 'saxony', 'austria', 'helvetia'],
  },
  helvetia: {
    name: 'Switzerland',
    capital: 'Geneva',
    isRegCapital: false,
    impassable: false,
    colorKey: '#01e1d4',
    nx: 0.4125,
    ny: 0.4475,
    neighbors: ['france', 'bavaria', 'piemonte'],
  },

  // --- EAST (Prussia, Austria, Russia) ---
  brandenburg: {
    name: 'Prussia',
    capital: 'Berlin',
    isRegCapital: true,
    impassable: false,
    colorKey: '#c6f4c6',
    nx: 0.525,
    ny: 0.25,
    neighbors: ['hanover', 'saxony', 'bohemia', 'east_prussia', 'poland'],
  },
  east_prussia: {
    name: 'East Prussia',
    capital: 'Königsberg',
    isRegCapital: true,
    impassable: false,
    colorKey: '#b23904',
    nx: 0.6125,
    ny: 0.20875,
    neighbors: ['brandenburg', 'poland', 'baltic_states'],
  },
  bohemia: {
    name: 'Bohemia',
    capital: 'Prague',
    isRegCapital: false,
    impassable: false,
    colorKey: '#dcfb4d',
    nx: 0.55,
    ny: 0.33375,
    neighbors: ['saxony', 'brandenburg', 'austria', 'poland'],
  },
  austria: {
    name: 'Austria',
    capital: 'Vienna',
    isRegCapital: true,
    impassable: false,
    colorKey: '#e000fa',
    nx: 0.5375,
    ny: 0.41625,
    neighbors: ['bavaria', 'bohemia', 'hungary', 'venetia', 'dalmatia'],
  },
  poland: {
    name: 'Poland',
    capital: 'Warsaw',
    isRegCapital: false,
    impassable: false,
    colorKey: '#05a599',
    nx: 0.61917,
    ny: 0.3125,
    neighbors: ['brandenburg', 'east_prussia', 'galicia', 'belarus', 'bohemia'],
  },
  galicia: {
    name: 'Galicia',
    capital: 'Lviv',
    isRegCapital: false,
    impassable: false,
    colorKey: '#994133',
    nx: 0.6875,
    ny: 0.35375,
    neighbors: ['poland', 'hungary', 'ukraine'],
  },
  hungary: {
    name: 'Hungary',
    capital: 'Budapest',
    isRegCapital: false,
    impassable: false,
    colorKey: '#949439',
    nx: 0.625,
    ny: 0.41625,
    neighbors: ['austria', 'galicia', 'serbia', 'wallachia', 'dalmatia'],
  },
  dalmatia: {
    name: 'Illyrian Province',
    capital: 'Ljubljana',
    isRegCapital: false,
    impassable: false,
    colorKey: '#35fd43',
    nx: 0.5375,
    ny: 0.5,
    neighbors: ['venetia', 'serbia', 'austria', 'hungary'],
  },

  // --- RUSSIAN EMPIRE (Far East) ---
  baltic_states: {
    name: 'Baltic States',
    capital: 'Riga',
    isRegCapital: false,
    impassable: false,
    colorKey: '#339910',
    nx: 0.68167,
    ny: 0.125,
    neighbors: ['sweden', 'east_prussia', 'belarus', 'moscow'],
  },
  belarus: {
    name: 'Belarus',
    capital: 'Smolensk',
    isRegCapital: false,
    impassable: false,
    colorKey: '#336610',
    nx: 0.70667,
    ny: 0.27125,
    neighbors: ['poland', 'baltic_states', 'moscow', 'ukraine'],
  },
  moscow: {
    name: 'Moscow',
    capital: 'Moscow',
    isRegCapital: true,
    impassable: false,
    colorKey: '#6bce10',
    nx: 0.875,
    ny: 0.16625,
    neighbors: ['belarus', 'ukraine', 'baltic_states'],
  },
  ukraine: {
    name: 'Ukraine',
    capital: 'Kiev',
    isRegCapital: false,
    impassable: false,
    colorKey: '#cee763',
    nx: 0.8625,
    ny: 0.33375,
    neighbors: ['belarus', 'moscow', 'galicia', 'wallachia'],
  },

  // --- SOUTH (Italy) ---
  piemonte: {
    name: 'Piedmont',
    capital: 'Turin',
    isRegCapital: false,
    impassable: false,
    colorKey: '#068598',
    nx: 0.4,
    ny: 0.51,
    neighbors: ['france', 'helvetia', 'lombardia', 'papal_states', 'venetia'],
  },
  lombardia: {
    name: 'Lombardy',
    capital: 'Milan',
    isRegCapital: true,
    impassable: false,
    colorKey: '#cefa00',
    nx: 0.44417,
    ny: 0.5,
    neighbors: ['piemonte', 'venetia', 'papal_states'],
  },
  venetia: {
    name: 'Venetia',
    capital: 'Venice',
    isRegCapital: false,
    impassable: false,
    colorKey: '#b24104',
    nx: 0.4875,
    ny: 0.49,
    neighbors: ['piemonte', 'austria', 'dalmatia', 'lombardia', 'papal_states'],
  },
  papal_states: {
    name: 'Papal States',
    capital: 'Rome',
    isRegCapital: true,
    impassable: false,
    colorKey: '#fece28',
    nx: 0.475,
    ny: 0.60375,
    neighbors: ['piemonte', 'lombardia', 'venetia', 'naples'],
  },
  naples: {
    name: 'Naples',
    capital: 'Naples',
    isRegCapital: true,
    impassable: false,
    colorKey: '#1ad701',
    nx: 0.5192,
    ny: 0.64625,
    neighbors: ['papal_states', 'tunisia'],
  },

  // --- SOUTH (Balkans) ---
  serbia: {
    name: 'Serbia',
    capital: 'Belgrade',
    isRegCapital: true,
    impassable: false,
    colorKey: '#ff9400',
    nx: 0.6375,
    ny: 0.54125,
    neighbors: ['dalmatia', 'hungary', 'wallachia', 'bulgaria', 'greece'],
  },
  wallachia: {
    name: 'Wallachia',
    capital: 'Bucharest',
    isRegCapital: false,
    impassable: false,
    colorKey: '#7be7e7',
    nx: 0.7125,
    ny: 0.47875,
    neighbors: ['hungary', 'serbia', 'bulgaria', 'ukraine'],
  },
  bulgaria: {
    name: 'Bulgaria',
    capital: 'Sofia',
    isRegCapital: false,
    impassable: false,
    colorKey: '#ceade7',
    nx: 0.7125,
    ny: 0.58375,
    neighbors: ['serbia', 'wallachia', 'greece', 'constantinople'],
  },
  greece: {
    name: 'Greece',
    capital: 'Athens',
    isRegCapital: false,
    impassable: false,
    colorKey: '#33e7e7',
    nx: 0.7125,
    ny: 0.72875,
    neighbors: ['bulgaria', 'serbia'],
  },

  // --- MEDITERRANEAN AND AFRICA (Background) ---
  constantinople: {
    name: 'Constantinople',
    capital: 'Konstantiniyye',
    isRegCapital: true,
    impassable: false,
    colorKey: '#fd35c2',
    nx: 0.7875,
    ny: 0.625,
    neighbors: ['bulgaria', 'levant'],
  },
  levant: {
    name: 'Levant',
    capital: 'Jerusalem',
    isRegCapital: false,
    impassable: false,
    colorKey: '#7e03bd',
    nx: 0.9375,
    ny: 0.875,
    neighbors: ['constantinople', 'egypt'],
  },
  egypt: {
    name: 'Egypt',
    capital: 'Cairo',
    isRegCapital: true,
    impassable: false,
    colorKey: '#d79801',
    nx: 0.8125,
    ny: 0.9375,
    neighbors: ['cyrenaica', 'levant'],
  },
  cyrenaica: {
    name: 'Cyrenaica',
    capital: 'Benghazi',
    isRegCapital: false,
    impassable: false,
    colorKey: '#9bf868',
    nx: 0.6192,
    ny: 0.85375,
    neighbors: ['tunisia', 'egypt'],
  },
  tunisia: {
    name: 'Tunisia',
    capital: 'Tunis',
    isRegCapital: false,
    impassable: false,
    colorKey: '#b98df5',
    nx: 0.4375,
    ny: 0.77125,
    neighbors: ['barbary', 'naples', 'cyrenaica'],
  },
  barbary: {
    name: 'Barbary',
    capital: 'Algiers',
    isRegCapital: false,
    impassable: false,
    colorKey: '#11ffb9',
    nx: 0.2375,
    ny: 0.77125,
    neighbors: ['spain', 'tunisia'],
  },

  // --- MOUNTAIN TERRITORIES (Background) ---
  mountains: {
    name: 'Alps',
    impassable: true,
    colorKey: '#000000',
    nx: 0,
    ny: 0,
    neighbors: [],
  },
};

// Utility function to scale normalized coordinates to canvas dimensions
export function createScaledTerritories(canvasWidth, canvasHeight) {
  const scaledTerritories = {};
  Object.entries(TERRITORIES_NORMALIZED).forEach(([id, territory]) => {
    scaledTerritories[id] = {
      ...territory,
      cx: territory.nx * canvasWidth,
      cy: territory.ny * canvasHeight,
    };
    delete scaledTerritories[id].nx;
    delete scaledTerritories[id].ny;
  });
  return scaledTerritories;
}

// Default export for current canvas size (1200x800)
export const TERRITORIES = createScaledTerritories(1200, 800);
